Backend/firebase-rails-modified/config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :houses do
      resources :rooms do
        resources :walls do
          resources :shelves do
            resources :books 
          end
        end
      end
    end
  end  
  
  
  namespace :api do 
    namespace :v1 do 
      
      resources :users do 
        resources :houses do
          resources :rooms do
            resources :walls do
              resources :shelves do
                resources :books
              end
            end
          end
        end
      end  
    end 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  namespace :api do 
    namespace :v1 do 
      
      # Send command to controller to do Google Api analisis   
      get '/users/:user_id/houses/:house_id/rooms/:room_id/walls/:wall_id/shelves/:shelf_id/search-on-google',
      to: 'books#search_on_google', as: "search_on_google"
      
      get '/get-user-by-token',
      to: 'users#get_user_by_token', as: "get_user_by_token"

      get '/get-user-by-email',
      to: 'users#get_user_by_email', as: "get_user_by_email"

      
      get '/getAllRooms/:user_id',
      to: 'rooms#allRooms', as: "allRooms"

      get '/getAllWalls/:user_id',
      to: 'walls#allWalls', as: "allWalls"

      get '/getAllShelves/:user_id',
      to: 'shelves#allShelves', as: "allShelves"
      
      get '/getAllBooks/:user_id',
      to: 'books#allBooks', as: "allBooks"

      get '/scan-all-books/:user_id',
      to: 'books#scanAllBooks'

    end
  end



end

Backend/firebase-rails-modified/app/models/wall.rb
class Wall < ApplicationRecord

  belongs_to :room
  has_many :shelves
  
  accepts_nested_attributes_for :shelves
  
  after_commit :sync_create

    def self.get_wall(wall_id)
      FIREBASE_DB.get('/walls/' + wall_id.to_s)
    end
  
    def sync_create
      add_wall
    end
  
    private
  
    def add_wall
      FIREBASE_DB.post('/walls/' + id.to_s, {
        name: name
      })
    end
end

Backend/firebase-rails-modified/app/controllers/api/v1/walls_controller.rb
class Api::V1::WallsController < ApiController

  before_action :get_user
  before_action :get_house
  before_action :get_room
  
  before_action :set_wall, only: [:show, :edit, :update, :destroy]

  # GET /walls
  # GET /walls.json
  def index
    walls = @room.walls
    render json: {status: 'SUCCESS', message: 'Loaded all walls', data: walls}, status: :ok
  end

  def allWalls
    houses=@user.houses
    rooms= houses.map(&:rooms).flatten()
    walls = rooms.map(&:walls).flatten()
    render json: {status: 'SUCCESS', message: 'Loaded all walls', data: walls}, status: :ok 
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
    wall = @wall
    render json: {status: 'SUCCESS', message: 'Loaded wall', data: [wall]}, status: :ok
  end

  # GET /walls/new
  # def new
  #   @wall = @room.walls.new
  # end

  # # GET /walls/1/edit
  # def edit
  # end

  # POST /walls
  # POST /walls.json
  def create
    @wall = @room.walls.new(wall_params)

      if @wall.save
        render json: {status: 'SUCCESS', message: 'Created wall', data: [@wall]}, status: :ok
      else
        render json: { json: 'Error in creation'}, status: 400
   end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    if @wall.update(wall_params)
    render json: {status: 'SUCCESS', message: 'Updated wall', data: [@wall]}, status: :ok
  else
    render json: { json: 'Error in update'}, status: 400
  end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    if @wall.destroy
      render json: {status: 'SUCCESS', message: 'Destroyed wall', data: [@wall]}, status: :ok
    else
      render json: { json: 'Error in destroy'}, status: 400

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def get_user
      @user = User.find(params[:user_id])
    end
    

    def get_house
      if(params[:house_id])
      @house = House.find(params[:house_id])
      end
    end
      
    
    def get_room
      if(params[:room_id])
      @room = Room.find(params[:room_id])
      end
    end
      

    
    def set_wall
      @wall = @room.walls.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.permit(:name,:user_id,:room_id,:house_id)
    end
end

Backend/firebase-rails-modified/app/controllers/walls_controller.rb
class WallsController < ApplicationController

  before_action :get_user
  before_action :get_house
  before_action :get_room
  
  before_action :set_wall, only: [:show, :edit, :update, :destroy]

  # GET /walls
  # GET /walls.json
  def index
    walls = @room.walls
    render json: {status: 'SUCCESS', message: 'Loaded all posts', data: walls}, status: :ok  end

  # GET /walls/1
  # GET /walls/1.json
  def show
    wall=@wall
    render json: {status: 'SUCCESS', message: 'Loaded all posts', data: wall}, status: :ok
  end

  # GET /walls/new
  def new
    @wall = @room.walls.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = @room.walls.new(wall_params)

    respond_to do |format|
      if @wall.save
        format.html { redirect_to user_house_room_walls_path(@user,@house,@room), notice: 'Wall was successfully created.' }
        format.json { render :show, status: :created, location: @wall }
      else
        format.html { render :new }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    respond_to do |format|
      if @wall.update(wall_params)
        format.html { redirect_to user_house_room_walls_path(@user,@house,@room), notice: 'Wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall }
      else
        format.html { render :edit }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @wall.destroy
    respond_to do |format|
      format.html { redirect_to user_house_rooms_path(@user,@house,@room), notice: 'Wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def get_user
      @user = User.find(params[:user_id])
    end
    

    def get_house
      @house = House.find(params[:house_id])
    end
      
    
    def get_room
      @room = Room.find(params[:room_id])
    end
      

    
    def set_wall
      @wall = @room.walls.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:name,:user_id,:house_id,:room_id)
    end
end

Backend/firebase-rails-modified/app/helpers/walls_helper.rb
module WallsHelper
end

Backend/firebase-rails-modified/app/views/walls/_form.html.erb
<%= form_for([@user,@house,@room,@wall]) do |form| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% wall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/firebase-rails-modified/app/views/walls/edit.html.erb
<h1>Editing Wall</h1>

<%= render 'form', wall: @wall %>

<%= link_to 'Show', user_house_room_walls_path(@user,@house,@room) %> |
<%= link_to 'Back', [@user,@house,@room] %>

Backend/firebase-rails-modified/app/views/walls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Walls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walls.each do |wall| %>
      <tr>
        <td><%= wall.name %></td>
        <td><%= link_to 'Show',[@user,@house,@room] %></td>
        <td><%= link_to 'Edit', edit_user_house_room_wall_path(@user,@house,@room,wall) %></td>
        <td><%= link_to 'Destroy', [@user,@house,@room,wall], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wall', new_user_house_room_wall_path(@user,@house,@room) %>

Backend/firebase-rails-modified/app/views/walls/new.html.erb
<h1>New Wall</h1>

<%= render 'form', wall: @wall %>

<%= link_to 'Back',  user_house_room_walls_path(@user,@house,@room)%>

Backend/firebase-rails-modified/app/views/walls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wall.name %>
</p>

<%= link_to 'Edit', edit_user_house_room_wall_path(@user,@house,@room,@wall) %> |
<%= link_to 'Back', user_house_room_walls_path(@user,@house,@room) %>