Backend/firebase-rails-modified/config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :houses do
      resources :rooms do
        resources :walls do
          resources :shelves do
            resources :books 
          end
        end
      end
    end
  end  
  
  
  namespace :api do 
    namespace :v1 do 
      
      resources :users do 
        resources :houses do
          resources :rooms do
            resources :walls do
              resources :shelves do
                resources :books
              end
            end
          end
        end
      end  
    end 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  namespace :api do 
    namespace :v1 do 
      
      # Send command to controller to do Google Api analisis   
      get '/users/:user_id/houses/:house_id/rooms/:room_id/walls/:wall_id/shelves/:shelf_id/search-on-google',
      to: 'books#search_on_google', as: "search_on_google"
      
      get '/get-user-by-token',
      to: 'users#get_user_by_token', as: "get_user_by_token"

      get '/get-user-by-email',
      to: 'users#get_user_by_email', as: "get_user_by_email"

      
      get '/getAllRooms/:user_id',
      to: 'rooms#allRooms', as: "allRooms"

      get '/getAllWalls/:user_id',
      to: 'walls#allWalls', as: "allWalls"

      get '/getAllShelves/:user_id',
      to: 'shelves#allShelves', as: "allShelves"
      
      get '/getAllBooks/:user_id',
      to: 'books#allBooks', as: "allBooks"

      get '/scan-all-books/:user_id',
      to: 'books#scanAllBooks'

    end
  end



end

Backend/firebase-rails-modified/app/controllers/api/v1/shelves_controller.rb
class Api::V1::ShelvesController < ApiController
  
  before_action :get_user
  before_action :get_house
  before_action :get_room
  before_action :get_wall
  
  before_action :set_shelf, only: [:show, :edit, :update, :destroy]
  
  # GET /shelves
  # GET /shelves.json
  def index
    shelves = @wall.shelves
    render json: {status: 'SUCCESS', message: 'Loaded all shelves', data: shelves}, status: :ok
  end


  def allShelves
    houses=@user.houses
    rooms= houses.map(&:rooms).flatten()
    walls = rooms.map(&:walls).flatten()
    shelves = walls.map(&:shelves).flatten()
    render json: {status: 'SUCCESS', message: 'Loaded all shelves', data: shelves}, status: :ok 
  end
  
  # GET /shelves/1
  # GET /shelves/1.json
  def show
    shelf = @shelf
    render json: {status: 'SUCCESS', message: 'Loaded shelf', data: [shelf]}, status: :ok
  end
  
  # # GET /shelves/new
  # def new
  #   @shelf = @wall.shelves.build
  # end
  
  # # GET /shelves/1/edit
  # def edit
  # end
  
  # POST /shelves
  # POST /shelves.json
  def create
    @shelf = @wall.shelves.build(shelf_params)
    
    if @shelf.save
      
      render json: {status: 'SUCCESS', message: 'Created shelf', data: [@shelf]}, status: :ok
    else
      render json: { json: 'Error in creation'}, status: 400
      
    end
  end
  
  # PATCH/PUT /shelves/1
  # PATCH/PUT /shelves/1.json
  def update
    
    if @shelf.update(shelf_params)
      
      render json: {status: 'SUCCESS', message: 'Updated shelf', data: [@shelf]}, status: :ok
    else
      render json: { json: 'Error in update'}, status: 400  
    end
  end
  
  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    if @shelf.destroy
      
      render json: {status: 'SUCCESS', message: 'Destroyed shelf', data: [@shelf]}, status: :ok
    else
      render json: { json: 'Error in destroy'}, status: 400
    end
  end
  
  private
  
  def get_user
    @user = User.find(params[:user_id])
  end
  
  
  def get_house
    if params[:house_id]
    @house = House.find(params[:house_id])
  end
  end
  
  
  def get_room
    if params[:room_id]
    @room = Room.find(params[:room_id])
    end
  end
  
  def get_wall
    if params[:wall_id]
    @wall = Wall.find(params[:wall_id])
    end
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_shelf
    @shelf = Shelf.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def shelf_params
    params.permit(:name,:user_id,:house_id,:room_id,:wall_id)
  end
end

Backend/firebase-rails-modified/app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  
  before_action :get_user
  before_action :get_house
  before_action :get_room
  before_action :get_wall
  
  before_action :set_shelf, only: [:show, :edit, :update, :destroy]
  
  # GET /shelves
  # GET /shelves.json
  def index
    @shelves = @wall.shelves
  end
  
  # GET /shelves/1
  # GET /shelves/1.json
  def show
  end
  
  # GET /shelves/new
  def new
    @shelf = @wall.shelves.build
  end
  
  # GET /shelves/1/edit
  def edit
  end
  
  # POST /shelves
  # POST /shelves.json
  def create
    @shelf = @wall.shelves.build(shelf_params)
    
    respond_to do |format|
      if @shelf.save
        format.html { redirect_to user_house_room_wall_shelf(:user_id,
        :house_id,:room_id,:wall_id,@shelf),
           notice: 'Shelf was successfully created.' }
        format.json { render :show, status: :created, location: @shelf }
      else
        format.html { render :new }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /shelves/1
  # PATCH/PUT /shelves/1.json
  def update
    respond_to do |format|
      if @shelf.update(shelf_params)
        format.html { redirect_to user_house_room_wall_shelf(:user_id,
          :house_id,:room_id,:wall_id,@shelf),
          notice: 'Shelf was successfully updated.' }
        format.json { render :show, status: :ok, location: @shelf }
      else
        format.html { render :edit }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    @shelf.destroy
    respond_to do |format|
      format.html { redirect_to user_house_room_wall_shelves(:user_id,
        :house_id,:room_id,:wall_id),
         notice: 'Shelf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  
  def get_user
    @user = User.find(params[:user_id])
  end
  
  
  def get_house
    @house = House.find(params[:house_id])
  end
  
  
  def get_room
    @room = Room.find(params[:room_id])
  end
  
  def get_wall
    @wall = Wall.find(params[:wall_id])
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_shelf
    @shelf = Shelf.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def shelf_params
    params.require(:shelf).permit(:name,:user_id,:house_id,:room_id,:wall_id)
  end
end

Backend/firebase-rails-modified/app/helpers/shelves_helper.rb
module ShelvesHelper
end

Backend/firebase-rails-modified/app/views/shelves/_form.html.erb
<%= form_with(model: shelf, local: true) do |form| %>
  <% if shelf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>

      <ul>
      <% shelf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/firebase-rails-modified/app/views/shelves/edit.html.erb
<h1>Editing Shelf</h1>

<%= render 'form', shelf: @shelf %>

<%= link_to 'Show', @shelf %> |
<%= link_to 'Back', shelves_path %>

Backend/firebase-rails-modified/app/views/shelves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shelves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shelves.each do |shelf| %>
      <tr>
        <td><%= shelf.name %></td>
        <td><%= link_to 'Show', user_house_room_wall_shelf_path(@user,
@house,@room,@wall,shelf) %></td>
        <td><%= link_to 'Edit', edit_user_house_room_wall_shelf_path(@user,
@house,@room,@wall,shelf) %></td>
        <td><%= link_to 'Destroy', shelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shelf', new_shelf_path %>

Backend/firebase-rails-modified/app/views/shelves/new.html.erb
<h1>New Shelf</h1>

<%= render 'form', shelf: @shelf %>

<%= link_to 'Back', shelves_path %>

Backend/firebase-rails-modified/app/views/shelves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shelf.name %>
</p>

<%= link_to 'Edit', edit_user_house_room_wall_shelf_path(@user,
@house,@room,@wall,@sheelf) %> |
<%= link_to 'Back', user_house_room_wall_shelves_path(@user,
@house,@room,@wall) %>