Backend/firebase-rails-modified/config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :houses do
      resources :rooms do
        resources :walls do
          resources :shelves do
            resources :books 
          end
        end
      end
    end
  end  
  
  
  namespace :api do 
    namespace :v1 do 
      
      resources :users do 
        resources :houses do
          resources :rooms do
            resources :walls do
              resources :shelves do
                resources :books
              end
            end
          end
        end
      end  
    end 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  namespace :api do 
    namespace :v1 do 
      
      # Send command to controller to do Google Api analisis   
      get '/users/:user_id/houses/:house_id/rooms/:room_id/walls/:wall_id/shelves/:shelf_id/search-on-google',
      to: 'books#search_on_google', as: "search_on_google"
      
      get '/get-user-by-token',
      to: 'users#get_user_by_token', as: "get_user_by_token"

      get '/get-user-by-email',
      to: 'users#get_user_by_email', as: "get_user_by_email"

      
      get '/getAllRooms/:user_id',
      to: 'rooms#allRooms', as: "allRooms"

      get '/getAllWalls/:user_id',
      to: 'walls#allWalls', as: "allWalls"

      get '/getAllShelves/:user_id',
      to: 'shelves#allShelves', as: "allShelves"
      
      get '/getAllBooks/:user_id',
      to: 'books#allBooks', as: "allBooks"

      get '/scan-all-books/:user_id',
      to: 'books#scanAllBooks'

    end
  end



end

Backend/firebase-rails-modified/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :shelf
end

Backend/firebase-rails-modified/app/controllers/api/v1/books_controller.rb
#require 'net/http'

require 'async'
require 'async/http/internet'
require 'uri'
require 'httparty'


class Api::V1::BooksController < ApiController
  
  
  before_action :get_user
  before_action :get_house
  before_action :get_room
  before_action :get_wall
  before_action :get_shelf
  
  
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  # GET /books
  # GET /books.json
  def index
    books = @shelf.books
    render json: {status: 'SUCCESS', message: 'Loaded all books', data: books}, status: :ok
  end
  
  # GET /books/1
  # GET /books/1.json
  def show
    book=@book
    render json: {status: 'SUCCESS', message: 'Loaded all book', data: [book]}, status: :ok
  end
  
  # GET all books for a user
  def allBooks
    houses=@user.houses
    rooms= houses.map(&:rooms).flatten() 
    walls=rooms.map(&:walls).flatten()
    shelves=walls.map(&:shelves).flatten()
    books=shelves.map(&:books).flatten()
    render json: {status: 'SUCCESS', message: 'Loaded all books', data: books}, status: :ok
  end
  
  
  
  # # GET /books/new
  # def new
  #   @book = @wall.books.build
  # end
  
  # # GET /books/1/edit
  # def edit
  # end
  
  # POST /books
  # POST /books.json
  def create
    @book = @shelf.books.build(book_params)
    
    if @book.save
      
      render json: {status: 'SUCCESS', message: 'Created book', data: [@book]}, status: :ok
    else
      render json: { json: 'Error in creation'}, status: 400
    end
  end
  
  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      render json: {status: 'SUCCESS', message: 'Updated book', data: [@book]}, status: :ok
    else
      render json: { json: 'Error in update'}, status: 400
    end
  end
  
  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.destroy
      
      render json: {status: 'SUCCESS', message: 'Destroyed book', data: [@book] }, status: :ok
    else
      render json: { json: 'Error in destroy'}, status: 400
    end
  end
  
  #GET /search-on-google
  def search_on_google
    books = @shelf.books
    puts "<<< Starting Async search"
    my_threads = []
    books.each do |b|
      puts "Starting thread for #{b.title}"
      my_threads << Thread.new{ google_search(b)} 
    end
    
    puts "Async search started >>>"
    render json: {status: 'SUCCESS', message: 'Search on Google request received', data: books}, status: :ok
  end
  
  #GET /scanAllBooks
  def scanAllBooks
    houses=@user.houses
    rooms= houses.map(&:rooms).flatten() 
    walls = rooms.map(&:walls).flatten()
    shelves = walls.map(&:shelves).flatten()
    books = shelves.map(&:books).flatten()
    puts "<<< Starting Async search"
    my_threads = []
    books.each do |b|
      puts "Starting thread for #{b.title}"
      my_threads << Thread.new{ google_search(b)} 
    end
    
    puts "Async search started >>>"
    render json: {status: 'SUCCESS', message: 'Search on Google request received', data: books}, status: :ok
  end
  
  
  
  private
  
  def google_search(book)
    puts "Analyzing #{book.title} from thread"
    url = "https://www.googleapis.com/books/v1/volumes?q="  
    url = url + book.title 
    url = URI.encode(url)
    response = HTTParty.get(url, format: :json)
    response = JSON.parse(response.body)["items"][0]
    
    #response.save("/tmp/search.html")
    #puts "Resonse:" + JSON.pretty_generate(response)+"..."
    book.googleData = response
    if book.save
     # puts "[V] Book #{book.title} #{book.googleData.last(10)} updated"
      puts "[V] Book #{book.title}  updated"
    else
      if room.errors.any?
        puts "[E] #{ book.errors.full_messages }"
      end
    end
  end
  
  def get_user
    if(params[:user_id])
      @user = User.find(params[:user_id])
    end
  end
  
  
  def get_house
    if(params[:house_id])
      @house = House.find(params[:house_id])
    end
  end
  
  
  def get_room
    if(params[:room_id])
      @room = Room.find(params[:room_id])
    end
  end
  
  def get_wall
    if(params[:wall_id])
      @wall = Wall.find(params[:wall_id])
    end
  end
  
  
  def get_shelf
    if(params[:shelf_id])
      @shelf = Shelf.find(params[:shelf_id])
    end
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    if(params[:id])
      @book = Book.find(params[:id])
    end
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.permit(:title, :authors, :publisher, :publishedDate, :description,
    :isbn, :pageCount, :categories, :imageLinks, :country, :price,
    :user_id,:house_id,:room_id,:wall_id,:shelf_id,
    :googleData,:small_thumbnail)
  end
end

Backend/firebase-rails-modified/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  
  before_action :get_user
  before_action :get_house
  before_action :get_room
  before_action :get_wall
  before_action :get_shelf
  
  
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  # GET /books
  # GET /books.json
  def index
    @books = @shelf.books
  end
  
  # GET /books/1
  # GET /books/1.json
  def show
  end
  
  # GET /books/new
  def new
    @book = @wall.books.build
  end
  
  # GET /books/1/edit
  def edit
  end
  
  # POST /books
  # POST /books.json
  def create
    @book = @wall.books.build(book_params)
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to user_house_room_wall_shelf_book(:user_id,
        :house_id,:room_id,:wall_id,:shelf_id,@book),
           notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to user_house_room_wall_shelf_book(:user_id,
          :house_id,:room_id,:wall_id,:shelf_id,@book),
          notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to user_house_room_wall_shelf_books(:user_id,
        :house_id,:room_id,:wall_id,:shelf_id),
         notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  
  def get_user
    @user = User.find(params[:user_id])
  end
  
  
  def get_house
    @house = House.find(params[:house_id])
  end
  
  
  def get_room
    @room = Room.find(params[:room_id])
  end
  
  def get_wall
    @wall = Wall.find(params[:wall_id])
  end
  

  def get_shelf
    @shelf = Shelf.find(params[:shelf_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :authors, :publisher, :publishedDate, :description,
      :isbn, :pageCount, :categories, :imageLinks, :country, :price,:user_id,:house_id,
      :room_id,:wall_id,:shelf_id)
    end
  end
  

Backend/firebase-rails-modified/app/helpers/books_helper.rb
module BooksHelper
end

Backend/firebase-rails-modified/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :publishedDate %>
    <%= form.date_select :publishedDate %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="field">
    <%= form.label :pageCount %>
    <%= form.text_field :pageCount %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.text_field :categories %>
  </div>

  <div class="field">
    <%= form.label :imageLinks %>
    <%= form.text_field :imageLinks %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/firebase-rails-modified/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

Backend/firebase-rails-modified/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Authors</th>
      <th>Publisher</th>
      <th>Publisheddate</th>
      <th>Description</th>
      <th>Isbn</th>
      <th>Pagecount</th>
      <th>Categories</th>
      <th>Imagelinks</th>
      <th>Country</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.publisher %></td>
        <td><%= book.publishedDate %></td>
        <td><%= book.description %></td>
        <td><%= book.isbn %></td>
        <td><%= book.pageCount %></td>
        <td><%= book.categories %></td>
        <td><%= book.imageLinks %></td>
        <td><%= book.country %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', user_house_room_wall_shelf_book_path(@user,
        @house,@room,@wall,@shelf,book) %></td>
        <td><%= link_to 'Edit', edit_user_house_room_wall_shelf_book_path(@user,
        @house,@room,@wall,@shelf,book) %></td>
        <td><%= link_to 'Destroy', user_house_room_wall_shelf_book_path(@user,
        @house,@room,@wall,@shelf,book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

Backend/firebase-rails-modified/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

Backend/firebase-rails-modified/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @book.authors %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Publisheddate:</strong>
  <%= @book.publishedDate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Pagecount:</strong>
  <%= @book.pageCount %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @book.categories %>
</p>

<p>
  <strong>Imagelinks:</strong>
  <%= @book.imageLinks %>
</p>

<p>
  <strong>Country:</strong>
  <%= @book.country %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>